export const ROUTES = {
  home: "/",
  cart: "/cart",
  search: "/search",
  checkout: "/checkout",
  account: "/account",
  login: "/account/login",
  register: "/account/register",
  wishlist: "/pages/wishlist",
  blog: "/blogs/tech-blog",
  collectionsIndex: "/collections",
  collections: {
    all: "/collections/shop-all",
    bestSellers: "/collections/best-sellers",
    keyboards: "/collections/mechanical-keyboards",
    mouse: "/collections/gaming-mouse-and-mousepad",
    chairs: "/collections/ergo-wfh-chairs",
    audio: "/collections/audio-video-and-lights",
    monitors: "/collections/monitors",
    newLaunches: "/collections/new-launches",
    controllers: "/collections/controllers",
  },
  product: (handle: string) => `/products/${handle}`,
  collection: (handle: string) => `/collections/${handle}`,
  page: (slug: string) => `/pages/${slug}`,
  policy: (slug: string) => `/policies/${slug}`,
} as const;
